FROM nginx:alpine

# Copia los archivos estáticos (HTML, CSS, JS, imágenes)
COPY . /usr/share/nginx/html

# Puerto de Nginx (80 por defecto)
EXPOSE 80

# No necesitas CMD, Nginx ya tiene uno por defecto
