apiVersion: v1
data:
  DB_PASSWORD: QXRhbGVzMTIzNA==
  DB_USER: YWRtaW4=
  GMAIL_APP_PASSWORD: bWtqZGxwcXBpd2xobm1ydA==
  GMAIL_USER: YXRhbG1lbmRvemEwM0BnbWFpbC5jb20=
kind: Secret
metadata:
  creationTimestamp: null
  name: backend-secret
  namespace: ambiente-atales-dev
