name: CI/CD Unificado - Backend y Frontend

on:
  push:
    branches:
      - main

env:
  DOCKER_USER: rociomagnoni
  BACKEND_IMAGE: rociomagnoni/backend-atales
  FRONTEND_IMAGE: rociomagnoni/frontend-atales
  MANIFESTS_REPO: RocioMagnoni/atales-k8s-cloud

jobs:
  build-publish-patch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v4

    - name: Obtener mensaje del último commit
      id: commit
      run: |
        COMMIT_MSG=$(git log -1 --pretty=%B)
        echo "mensaje_commit=$COMMIT_MSG" >> $GITHUB_OUTPUT

    - name: Detectar overlay según mensaje del commit
      id: overlay
      run: |
        MSG="${{ steps.commit.outputs.mensaje_commit }}"
        if [[ "$MSG" == *"[deploy-dev]"* ]]; then
          echo "overlay=dev" >> $GITHUB_OUTPUT
        elif [[ "$MSG" == *"[deploy-test]"* ]]; then
          echo "overlay=stg" >> $GITHUB_OUTPUT
        elif [[ "$MSG" == *"[deploy-prod]"* && "$MSG" == *"[approved]"* ]]; then
          echo "overlay=prod" >> $GITHUB_OUTPUT
        else
          echo "overlay=none" >> $GITHUB_OUTPUT
        fi

    - name: Cancelar si no es un commit de deploy
      if: steps.overlay.outputs.overlay == 'none'
      run: |
        echo "No es un commit de deploy. Abortando workflow."
        exit 0

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Definir tag de la imagen
      run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build y push backend
      run: |
        docker build -t $BACKEND_IMAGE:$IMAGE_TAG ./backend
        docker push $BACKEND_IMAGE:$IMAGE_TAG

    - name: Build y push frontend
      run: |
        docker build -t $FRONTEND_IMAGE:$IMAGE_TAG ./frontend
        docker push $FRONTEND_IMAGE:$IMAGE_TAG

    - name: Clonar manifiestos K8s
      uses: actions/checkout@v4
      with:
        repository: ${{ env.MANIFESTS_REPO }}
        token: ${{ secrets.K8S_REPO_PAT }}
        path: atales-k8s-cloud

    - name: Parchar deployment con nuevo tag
      run: |
        OVERLAY=${{ steps.overlay.outputs.overlay }}
        echo "Actualizando deployments con tag $IMAGE_TAG"
        sed -i "s|image: $BACKEND_IMAGE:.*|image: $BACKEND_IMAGE:$IMAGE_TAG|g" atales-k8s-cloud/overlays/$OVERLAY/patch-backend-deployment.yaml
        sed -i "s|image: $FRONTEND_IMAGE:.*|image: $FRONTEND_IMAGE:$IMAGE_TAG|g" atales-k8s-cloud/overlays/$OVERLAY/patch-frontend-deployment.yaml

    - name: Commit y push de los manifiestos
      run: |
        cd atales-k8s-cloud
        git config user.name "GitHub Actions"
        git config user.email "ci@github.com"
        git add overlays/${{ steps.overlay.outputs.overlay }}/*.yaml
        git commit -m "ci: patch $IMAGE_TAG para ${{ steps.overlay.outputs.overlay }}" || echo "Nada para commitear"
        git push

